
# Pokemon Red RL Training Configuration
# Generated by quickstart.py

# Hardware-optimized settings
NUM_ENVS = 16
TOTAL_TIMESTEPS = 10000000
SAVE_FREQ = 50_000

# Training hyperparameters
LEARNING_RATE = 3e-4
N_STEPS = 2048
BATCH_SIZE = 512
N_EPOCHS = 1
GAMMA = 0.999
GAE_LAMBDA = 0.95

# Environment settings
ROM_PATH = 'PokemonRed.gb'
HEADLESS = True
ACTION_FREQ = 24
MAX_STEPS = 8192
SAVE_SCREENSHOTS = True
